micronaut:
  application:
    name: freshbooksAuth
  security:
    authentication: cookie
    oauth2:
      clients:
        freshbooks:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          authorization:
            url: https://auth.freshbooks.com/service/auth/oauth/authorize
          scopes: admin:all:legacy
          token:
            url: https://api.freshbooks.com/auth/oauth/token
            auth-method: client-secret-post
          revocation:
            url: https://api.freshbooks.com/auth/oauth/revoke
            auth-method: client-secret-post
    endpoints:
      logout:
        get-allowed: true
    reject-not-found: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '${JWT_SECRET}'
              jws-algorithm: HS256
        generator:
          access-token:
            expiration: 43200
              
  ssl:
    enabled: true
    build-self-signed: true
    port: 443
